name: build
on:
  push:
    branches:
      - master
  release:
    types:
      - created

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/voicevox_engine

jobs:
  # Build Linux binary (push only buildcache image)
  build-linux:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          tag: build-env-with-binary-cpu-ubuntu20.04-latest
          runtime_tag: cpu-ubuntu20.04 # for cache use
          target: build-env-with-binary
          base_image: ubuntu:focal
          base_runtime_image: ubuntu:focal
          inference_device: cpu
          libtorch_url: https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.9.0%2Bcpu.zip
          nuitka_cache_path: nuitka_cache

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build run.py with Nuitka during docker build
      - name: Cache Nuitka (ccache, module-cache)
        uses: actions/cache@v2
        id: nuitka-cache
        with:
          path: ${{ matrix.nuitka_cache_path }}
          key: ${{ runner.os }}-nuitka-${{ matrix.target }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nuitka-${{ matrix.target }}-

      # error: failed to solve: failed to compute cache key: "/cache/Nuitka" not found: not found
      - name: Create cache dir (prevent cache key not found error)
        run: |
          mkdir -p "${{ nuitka_cache_path }}"

      # NOTE: `load: true` may silently fail when the GitHub Actions disk (14GB) is full.
      # https://docs.github.com/ja/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
      - name: Build binary during docker build
        uses: docker/build-push-action@v2
        env:
          IMAGE_TAG: ${{ env.IMAGE_NAME }}:${{ matrix.tag }}${{ (matrix.tag != '' && '-') || '' }}latest
          RUNTIME_IMAGE_TAG: ${{ env.IMAGE_NAME }}:${{ matrix.runtime_tag }}${{ (matrix.runtime_tag != '' && '-') || '' }}latest
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Dockerfile
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
            BASE_RUNTIME_IMAGE=${{ matrix.base_runtime_image }}
            INFERENCE_DEVICE=${{ matrix.inference_device }}
            LIBTORCH_URL=${{ matrix.libtorch_url }}
            HOST_NUITKA_CACHE_DIR=${{ nuitka_cache_path }}
          target: ${{ matrix.target }}
          load: true
          tags: |
            ${{ env.IMAGE_TAG }}
          cache-from: |
            type=registry,ref=${{ env.IMAGE_TAG }}-buildcache
            type=registry,ref=${{ env.RUNTIME_IMAGE_TAG }}-buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_TAG }}-buildcache,mode=max

      # Extract binary
      - name: Extract run.py binary from local Docker image
        env:
          IMAGE_TAG: ${{ env.IMAGE_NAME }}:${{ matrix.tag }}${{ (matrix.tag != '' && '-') || '' }}latest
        run: |
          CID=$(docker run --rm -d "${{ env.IMAGE_TAG }}" tail -f /dev/null)
          docker cp "${CID}:/opt/voicevox_engine_build" "$(readlink -f "build")"
          docker rm -f "${CID}"

      - uses: actions/upload-artifact@v2
        with:
          name: run.dist
          path: build/run.dist/
